fixing bug

diff --git a/sample-java-app/environments/ci/tasks/10-gitops.yaml b/sample-java-app/environments/ci/tasks/10-gitops.yaml
--- a/sample-java-app/environments/ci/tasks/10-gitops.yaml
+++ b/sample-java-app/environments/ci/tasks/10-gitops.yaml
@@ -11,30 +11,48 @@ metadata:
     version: 0.0.0
 spec:
   params:
+    - name: git-url
+    - name: git-revision
+      default: master
+    - name: source-dir
+      default: /source
+    - name: image-server
+      default: ""
+    - name: image-namespace
+      default: ""
+    - name: image-repository
+      default: ""
+    - name: image-tag
+      default: ""
     - name: app-name
       default: ""
-    - name: version
+    - name: app-path
       default: ""
+    - name: environment
+      default: ""
+    - name : security
+      default: ""
+    - name: ha
+      default: ""
+    - name: deploy-ingress-type
+      default: "route"
+    - name: tools-image
+      default: quay.io/ibmgaragecloud/ibmcloud-dev:v2.0.4
     - name: src-environment
       default: ""
     - name: dest-environment
       default: ""
-    - name: app-path
-      default: ""
-    - name: source-dir
-      default: /source
     - name: subdir
       default: ""
     - name: parentdir
       default: ""
-    - name: yaml
-      default: "requirements.yaml"
-    - name: helm-url
-      default: ""
     - name: git-pr
       default: "false"
-    - name: tools-image
-      default: quay.io/ibmgaragecloud/ibmcloud-dev:v2.0.4
+    - name: yaml
+      default: "kubernetes"
+  results:
+    - name: service-port
+    - name: resource-type
   volumes:
     - name: source
       emptyDir: {}
@@ -43,6 +61,98 @@ spec:
       - name: source
         mountPath: $(params.source-dir)
   steps:
+    - name: git-clone
+      image: quay.io/ibmgaragecloud/alpine-git
+      env:
+        - name: GIT_PASSWORD
+          valueFrom:
+            secretKeyRef:
+              name: git-credentials
+              key: password
+              optional: true
+        - name: GIT_USERNAME
+          valueFrom:
+            secretKeyRef:
+              name: git-credentials
+              key: username
+              optional: true
+      script: |
+        set +x
+        if [[ -n "${GIT_USERNAME}" ]] && [[ -n "${GIT_PASSWORD}" ]]; then
+            git clone "$(echo $(params.git-url) | awk -F '://' '{print $1}')://${GIT_USERNAME}:${GIT_PASSWORD}@$(echo $(params.git-url) | awk -F '://' '{print $2}')" $(params.source-dir)
+        else
+            set -x
+            git clone $(params.git-url) $(params.source-dir)
+        fi
+        set -x
+        cd $(params.source-dir)
+        git checkout $(params.git-revision)
+    - name: replace-image
+      image: $(params.tools-image)
+      workingDir: $(params.source-dir)
+      env:
+        - name: TLS_SECRET_NAME
+          valueFrom:
+            configMapKeyRef:
+              name: ibmcloud-config
+              key: TLS_SECRET_NAME
+              optional: true
+        - name: INGRESS_SUBDOMAIN
+          valueFrom:
+            configMapKeyRef:
+              name: ibmcloud-config
+              key: INGRESS_SUBDOMAIN
+              optional: true
+      script: |
+          #!/usr/bin/env bash
+          set -ex
+          GIT_URL="$(params.git-url)"
+          GIT_REVISION="$(params.git-revision)"
+          APP_NAME="$(params.app-name)"
+          IMAGE_SERVER="$(params.image-server)"
+          IMAGE_NAMESPACE="$(params.image-namespace)"
+          IMAGE_REPOSITORY="$(params.image-repository)"
+          IMAGE_URL="${IMAGE_SERVER}/${IMAGE_NAMESPACE}/${IMAGE_REPOSITORY}"
+          IMAGE_VERSION="$(params.image-tag)"
+
+          if [[ $APP_NAME == *"qm"* ]] ; then
+            if [[ "$(params.ha)" == "true" ]] ; then
+              export YAML_ROOT="$(params.yaml)/native-ha-qmgr"
+            else
+              export YAML_ROOT="$(params.yaml)/generic-qmgr"
+            fi
+          else
+            export YAML_ROOT="$(params.yaml)"
+          fi
+
+          echo "YAML_ROOT: $YAML_ROOT"
+
+          if [[ -f "$YAML_ROOT/queuemanager.yaml" ]]; then
+            export YAML="$YAML_ROOT/queuemanager.yaml"
+          elif [[ -f "$YAML_ROOT/deployment.yaml" ]]; then
+            export YAML="$YAML_ROOT/deployment.yaml"
+          elif [[ -f statefulset.yaml ]]; then
+            export YAML="$YAML_ROOT/statefulset.yaml"
+          else
+            echo "Error: No deployment file is detected"
+            exit 1
+          fi
+
+          echo "YAML: $YAML"
+          export YAML_NEW="./$YAML-new.yaml"
+          echo "YAML_NEW: $YAML_NEW"
+
+          PREFIX=""
+          if [[ -f "${YAML}" ]]; then
+            sed "/image/ s|replace|${IMAGE_URL}:${IMAGE_VERSION}|g" $YAML > $YAML_NEW
+            cat ${YAML_NEW}
+            mv ${YAML_NEW} ${YAML}
+       
+            # rm ${YAML_NEW}
+
+          fi
+      securityContext:
+        privileged: true
     - name: gitops
       image: $(params.tools-image)
       workingDir: $(params.source-dir)
@@ -104,74 +214,19 @@ spec:
       script: |
           #!/usr/bin/env bash
           set -ex
-
           APP_NAME="$(params.app-name)"
-
           SUBDIR="$(params.subdir)"
-
           if [[ -z "${SUBDIR}" ]]; then
             SUBDIR="${APP_NAME}"
           fi
-
-          if [[ -n "$(params.parentdir)" ]]; then
-            if [[ -n "$(params.src-environment)" ]]; then
-              PARENT_DIR_SRC="$(params.parentdir)/$(params.app-path)/$(params.src-environment)"
-            fi
-            if [[ -n "$(params.dest-environment)" ]]; then
-              PARENT_DIR_DEST="$(params.parentdir)/$(params.app-path)/$(params.dest-environment)"
-            else
-              echo "Please set destination environment"
-            fi
-          elif [[ -n "${GIT_PARENT_DIR}" ]] && [[ "${GIT_PARENT_DIR}" = "bash -c"* ]]; then
-            if [[ -n "$(params.src-environment)" ]]; then
-              PARENT_DIR_SRC=$(eval $GIT_PARENT_DIR | tail -n 1)"/$(params.app-path)/$(params.src-environment)"
-            fi
-            if [[ -n "$(params.dest-environment)" ]]; then
-              PARENT_DIR_DEST=$(eval $GIT_PARENT_DIR | tail -n 1)"/$(params.app-path)/$(params.dest-environment)"
-            else
-              echo "Please set destination environment"
-            fi
-          elif [[ -n "${GIT_PARENT_DIR}" ]]; then
-            if [[ -n "$(params.src-environment)" ]]; then
-              PARENT_DIR_SRC="${GIT_PARENT_DIR}/$(params.app-path)/$(params.src-environment)"
-            fi
-            if [[ -n "$(params.dest-environment)" ]]; then
-              PARENT_DIR_DEST="${GIT_PARENT_DIR}/$(params.app-path)/$(params.dest-environment)"
-            else
-              echo "Please set destination environment"
-            fi
-          else
-            if [[ -n "$(params.src-environment)" ]]; then
-              PARENT_DIR_SRC="."
-            fi
-            if [[ -n "$(params.dest-environment)" ]]; then
-              PARENT_DIR_DEST="."
-            else
-              echo "Please set destination environment"
-            fi
-          fi
-
-          if [[ -n "$(params.src-environment)" ]]; then
-            SUBDIR_SRC="${PARENT_DIR_SRC}/${SUBDIR}"
-          fi
-          if [[ -n "$(params.dest-environment)" ]]; then
-            SUBDIR_DEST="${PARENT_DIR_DEST}/${SUBDIR}"
-          else
-            echo "Please set destination environment"
-          fi
-
           PROTOCOL="${GIT_PROTOCOL}"
           if [[ -z "${PROTOCOL}" ]]; then
             PROTOCOL="https"
           fi
-
-          YAML_FILE="$(params.yaml)"
-
           if [[ -z "${GIT_HOST}" ]] || [[ -z "${GIT_ORG}" ]] || [[ -z "${GIT_REPO}" ]]; then
               echo "GitOps repo has not been configured with confimap gitops-repo. Skipping trigger step"
               exit 0
           fi
-
           set +x
           if [[ -n "${GIT_USERNAME}" ]]; then
             GIT_AUTH_USER="${GIT_USERNAME}"
@@ -181,12 +236,10 @@ spec:
             exit 1
           fi
           set -x
-
           BRANCH_CMD=""
           if [[ -n "${GIT_BRANCH}" ]]; then
             BRANCH_CMD="-b ${GIT_BRANCH}"
           fi
-
           git config --global user.email "gitops@cloudnativetoolkit.dev"
           git config --global user.name "Cloud Native Toolkit Pipeline"
           echo "git clone ${BRANCH_CMD} ${PROTOCOL}://${GIT_AUTH_USER}:xxxx@${GIT_HOST}/${GIT_ORG}/${GIT_REPO}"
@@ -195,104 +248,56 @@ spec:
           git clone ${BRANCH_CMD} ${GIT_URL} gitops_cd
           set -x
           cd gitops_cd
-
-          if [[ -z "$(params.src-environment)" ]]; then
-            VERSION="$(params.version)"
-            HELM_URL="$(params.helm-url)"
+          if [[ $APP_NAME == *"qm"* ]]; then
+            if [[ "$(params.ha)" == "true" ]] ; then
+              export SOURCE_DIR="../$(params.yaml)/native-ha-qmgr"
+            else
+              export SOURCE_DIR="../$(params.yaml)/generic-qmgr"
+            fi
           else
-            VERSION="$(grep 'version:' ./$(params.app-path)/$(params.src-environment)/$(params.app-name)/${YAML_FILE} | awk 'NR==1{print $2}')"
-            HELM_URL="$(grep 'repository:' ./$(params.app-path)/$(params.src-environment)/$(params.app-name)/requirements.yaml | awk 'NR==1{print $2}')"
+            export SOURCE_DIR="../$(params.yaml)"
+          fi
+          if [[ -f "$SOURCE_DIR/queuemanager.yaml" ]]; then
+            cp -r "$SOURCE_DIR"/queuemanager.yaml $(params.app-path)/$(params.environment)/${SUBDIR}/queuemanager
+          elif [[ -f "$SOURCE_DIR/deployment.yaml" ]]; then
+            cp -r "$SOURCE_DIR"/deployment.yaml $(params.app-path)/$(params.environment)/${SUBDIR}/deployment
+          elif [[ -f statefulset.yaml ]]; then
+            cp -r "$SOURCE_DIR"/statefulset.yaml $(params.app-path)/$(params.environment)/${SUBDIR}/deployment
+          else
+            echo "No change in deployment file"
           fi
 
-          if [[ -z "${SUBDIR_SRC}" && -f "${SUBDIR_DEST}/${YAML_FILE}" ]]; then
-            echo "Requirements before update"
-            cat "${SUBDIR_DEST}/${YAML_FILE}"
+          if ls $SOURCE_DIR/*.sample-java-appsc &> /dev/null; then
+            cp -r "$SOURCE_DIR"/*.sample-java-appsc $(params.app-path)/$(params.environment)/"${SUBDIR}"/configmap
+          fi
 
-            yq r "${SUBDIR_DEST}/${YAML_FILE}" -j | \
-              jq --arg APP_NAME "${APP_NAME}" --arg VERSION "${VERSION}" --arg REPO "${HELM_URL}" '.dependencies |= map((select(.name == $APP_NAME) | .version = $VERSION | .repository = $REPO) // .)' | \
-              yq r --prettyPrint - > "${SUBDIR_DEST}/${YAML_FILE}.new"
+          if ls $SOURCE_DIR/*.ini &> /dev/null; then
+            cp -r "$SOURCE_DIR"/*.ini $(params.app-path)/$(params.environment)/"${SUBDIR}"/configmap
+          fi
 
-            rm "${SUBDIR_DEST}/${YAML_FILE}"
-            mv "${SUBDIR_DEST}/${YAML_FILE}.new" "${SUBDIR_DEST}/${YAML_FILE}"
+          if ls $SOURCE_DIR/configmap*.yaml &> /dev/null; then
+            cp -r "$SOURCE_DIR"/configmap*.yaml $(params.app-path)/$(params.environment)/"${SUBDIR}"/configmap
+          fi
 
-            echo "Requirements after update"
-            cat "${SUBDIR_DEST}/${YAML_FILE}"
-
-          elif [[ ! -z "${SUBDIR_SRC}" && -f "${SUBDIR_DEST}/${YAML_FILE}" ]]; then
-            echo "Requirements before update"
-            cat "${SUBDIR_DEST}/${YAML_FILE}"
-
-            # rm -rf ${SUBDIR_DEST}/${YAML_FILE} && cp -r ${SUBDIR_SRC}/${YAML_FILE} ${SUBDIR_DEST}/${YAML_FILE}
-
-            yq r "${SUBDIR_DEST}/${YAML_FILE}" -j | \
-              jq --arg APP_NAME "${APP_NAME}" --arg VERSION "${VERSION}" --arg REPO "${HELM_URL}" '.dependencies |= map((select(.name == $APP_NAME) | .version = $VERSION | .repository = $REPO) // .)' | \
-              yq r --prettyPrint - > "${SUBDIR_DEST}/${YAML_FILE}.new"
-
-            rm "${SUBDIR_DEST}/${YAML_FILE}"
-            mv "${SUBDIR_DEST}/${YAML_FILE}.new" "${SUBDIR_DEST}/${YAML_FILE}"
-
-            echo "Requirements after update"
-            cat "${SUBDIR_DEST}/${YAML_FILE}"
-
-          elif [[ -n "${HELM_URL}" ]]; then
-            if [[ ! -z ${SUBDIR_DEST} ]]; then
-              files=$(ls ${SUBDIR_DEST} | wc -l)
-              if [[ ${files} -gt 1 && ${files} -lt 3 ]]; then
-                echo "${SUBDIR_DEST} is present but files are not existing"
-                rm -rf ${SUBDIR_DEST}
-              fi
-            fi
-            echo "Creating first time chart using ${SUBDIR_DEST}"
-            # create directory
-            mkdir -p "${SUBDIR_DEST}"
-
-            # WARNING: Do not indent the cat commands below
-
-          cat <<EOF >"${SUBDIR_DEST}/Chart.yaml"
-          apiVersion: v2
-          version: 0.1.0
-          name: ${APP_NAME}
-          description: Chart to configure ArgoCD with the ${APP_NAME} project and its applications
-          EOF
-
-          cat <<EOF >"${SUBDIR_DEST}/${YAML_FILE}"
-          dependencies:
-            - name: ${APP_NAME}
-              version: ${VERSION}
-              repository: ${HELM_URL}
-          EOF
-
-          cat <<EOF >"${SUBDIR_DEST}/values.yaml"
-          global: {}
-          ${APP_NAME}:
-            replicaCount: 1
-          EOF
-
-          else
-            echo "GitOps repo configured but unable to update application config"
-            exit 1
+          if ls $SOURCE_DIR/*secret*.yaml &> /dev/null; then
+            cp -r "$SOURCE_DIR"/*secret*.yaml $(params.app-path)/$(params.environment)/"${SUBDIR}"/secrets
           fi
 
           APP_VERSION="$(git rev-parse HEAD | cut -c 1-8)"
-
           if [[ $(git status -s | wc -l) -eq 0 ]]; then
             echo "No changes"
             exit 0
           elif [[ "$(params.git-pr)" = "false" ]]; then
-            git add "${SUBDIR_DEST}/"
+            git add .
             git commit -m "Updates ${APP_NAME} to ${VERSION}"
             git push -v
           else
             git checkout -b cntk-ci-pipeline-${APP_NAME}-${APP_VERSION}
-
             # push changes to git
             git status
             git add "${SUBDIR_DEST}/"
             git commit -m "Cloudnative toolkit pipeline updates ${APP_NAME}" --no-edit --signoff
-
             git push origin cntk-ci-pipeline-${APP_NAME}-${APP_VERSION}
-
             GIT_PUSH_URL="${PROTOCOL}://api.github.com/repos/${GIT_ORG}/${GIT_REPO}/pulls"
             curl -u ${GIT_AUTH_USER}:${GIT_AUTH_PWD} -d '{"title":"PR to promote to '$(params.dest-environment)' for '$(params.app-name)'","base":"'${GIT_BRANCH}'", "head":"'${GIT_ORG}':cntk-ci-pipeline-'${APP_NAME}'-'${APP_VERSION}'"}' ${GIT_PUSH_URL}
-
           fi
